name = "hugo-theme-console-dark"
license = "MIT"
licenselink = "https://github.com/gryffyn/hugo-theme-console-dark/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console, now with grey and pink! Fork of hugo-theme-console."
homepage = "https://github.com/gryffyn/hugo-theme-console-dark"
tags = ["blog", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro"]
features = ["responsive"]
min_version = "0.69.0"

[author]
    name = "Lily Sinclair"
    homepage = "https://neveris.one"
    github = "https://github.com/gryffyn"

[original]
    name = "Marcin Mierzejewski"
    homepage = "https://mrmierzejewski.com"
    github = "https://github.com/mrmierzejewski"
